export const data = [
    {
        id: 'gitworkshop',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopfgfcys',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopsdzghbjna',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopzgdfhx',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopgxbgzds',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshop463athbz',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopdzsh',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopzse53',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopzb4544',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopfhsjnexbge',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
    {
        id: 'gitworkshopaSEDABW',
        title: "Github workshop",
        date: "12/11/2019",
        shortDes: 'Labore aliquip est magna id excepteur mollit eu minim minim laborum adipisicing nulla. Adipisicing labore velit incididunt incididunt. In qui cillum ad elit sunt mollit occaecat eiusmod. Tempor excepteur tempor aliqua culpa dolore consectetur. Aute fugiat occaecat sit Lorem ad duis ut aliqua duis tempor est fugiat cupidatat duis.',
        des: "Enim non nostrud culpa amet et cupidatat labore ut est laborum reprehenderit. Consequat do ea non cupidatat occaecat exercitation voluptate voluptate excepteur. Dolor cupidatat consequat magna duis voluptate. Amet velit ex cupidatat ea proident reprehenderit minim duis ea fugiat laboris dolore fugiat duis. Ut dolore ad deserunt laboris fugiat reprehenderit elit do quis dolore nisi tempor sit labore. Nostrud cillum quis esse cupidatat consectetur cillum voluptate aliquip. Mollit ea ea elit officia in commodo aliqua exercitation.Mollit laboris ut consectetur reprehenderit.Exercitation sit deserunt aliquip anim Lorem culpa aliqua officia sit duis pariatur consequat magna.Officia esse est culpa velit est sint nisi aute labore nulla non.Est culpa cupidatat esse officia veniam do dolore ex amet veniam culpa reprehenderit Lorem.Labore consectetur ad sit laboris.Anim aliquip tempor sunt deserunt veniam eiusmod quis aliquip commodo mollit.Voluptate sint sit nisi consectetur et magna sit.Magna ipsum adipisicing duis nisi excepteur commodo sunt excepteur labore adipisicing.Aliqua et eiusmod ex eu consequat nisi officia dolor deserunt minim.Esse non minim aliquip voluptate nostrud voluptate laborum pariatur id non officia.Dolor in aute occaecat nisi id dolore deserunt eu."
    },
]